add_library(entities OBJECT
    bomb.cpp
    breakabletile.cpp
    bridgeobject.cpp
    bridgesurf.cpp
    checkpoint.cpp
    entitymath.cpp
    explodedebris.cpp
    factory.cpp
    foe.cpp
    foepath.cpp
    framepose.cpp
    generators.cpp
    liftobject.cpp
    movableentity.cpp
    objectremove.cpp
    player.cpp
    slideobject.cpp
    splinepath.cpp
    wrapperobject.cpp)
target_include_directories(entities PRIVATE
    .
    ../audiodev
    ../app
    ../audio
    ../core
    ../level
    ../render
    ../ui)
