/* gamestr.h -- the game's own strings, now ours.
 *
 * These were the game's bytes at the game's addresses (COHESION_PLAN.md
 * Band 7b), because the game compared some of them by pointer.  No game
 * code that could compare them is left, so each is now our own array with
 * the original's bytes, generated by `tools/owndata.py strings` -- which
 * checked every address for a user in the remaining original code or a
 * pointer to it stored in the image, and found none (ENDGAME_PLAN.md,
 * "Direction").
 *
 * `inline` gives each array one address across every TU, so pointer
 * comparisons between our own files still hold.  The trailing comment keeps
 * the original address as provenance.  Names are GS_<GROUP>_<WHAT>; the
 * group is the subsystem, which is also how the game's .data lays them out.
 */
#ifndef KAROO_GAMESTR_H
#define KAROO_GAMESTR_H

/* --- ANI: ani.cpp -- the animation loader --- */
inline const char GS_ANI_LOADED[] = "ANI: %s loaded";  /* 0x004640b0: "ANI: %s loaded" */

/* --- FMT: shared one-conversion formats, used by several files --- */
inline const char GS_FMT_S[] = "%s";  /* 0x004641f8: "%s" */
inline const char GS_FMT_NEWLINE[] = "\012";  /* 0x00465160: "\n" */
inline const char GS_FMT_TAB[] = "\011";  /* 0x00465e00: "\t" */
inline const char GS_FMT_D[] = "%d";  /* 0x004668b8: "%d" */

/* --- CD: cdthemes.cpp -- the CD player --- */
inline const char GS_CD_TRY_TRACK[] = "CDM: trying to play track %d caption:%s ";  /* 0x00464398: "CDM: trying to play track %d caption:%s " */
inline const char GS_CD_TRACK9_LEN[] = "02:17:74";  /* 0x004643c4: "02:17:74" */
inline const char GS_CD_TRACK8_LEN[] = "04:00:74";  /* 0x004643d0: "04:00:74" */
inline const char GS_CD_TRACK7_LEN[] = "03:32:60";  /* 0x004643dc: "03:32:60" */
inline const char GS_CD_TRACK6_LEN[] = "03:08:54";  /* 0x004643e8: "03:08:54" */
inline const char GS_CD_TRACK5_LEN[] = "02:46:68";  /* 0x004643f4: "02:46:68" */
inline const char GS_CD_TRACK4_LEN[] = "03:28:39";  /* 0x00464400: "03:28:39" */
inline const char GS_CD_TRACK3_LEN[] = "02:59:12";  /* 0x0046440c: "02:59:12" */
inline const char GS_CD_TRACK2_LEN[] = "04:38:71";  /* 0x00464418: "04:38:71" */
inline const char GS_CD_TRACKFILE_PATH[] = "%s\134CDTracks\134%s.cdt";  /* 0x00464384: "%s\\CDTracks\\%s.cdt" */
inline const char GS_CD_TRACKFILE_DELIMS[] = " ,\011\012;";  /* 0x0046437c: " ,\t\n;" */
inline const char GS_CD_TRACKFILE_MODE[] = "r+t";  /* 0x00464378: "r+t" */
inline const char GS_CD_TRACKFILE_MISSING[] = "CDM: warning - track-file named as %s was not found";  /* 0x004642fc: "CDM: warning - track-file named as %s was not found" */
inline const char GS_CD_TRACKFILE_FOUND[] = "CDM: track-file named as %s was found";  /* 0x00464350: "CDM: track-file named as %s was found" */
inline const char GS_CD_THEME_TRACK[] = "CDM: theme %s is cd track %d";  /* 0x00464330: "CDM: theme %s is cd track %d" */
inline const char GS_CD_TRACK_COUNT[] = "CDM: number of tracks %d";  /* 0x0046443c: "CDM: number of tracks %d" */
inline const char GS_CD_TRACK_LENGTH[] = "CDM: track %d lenght:%s";  /* 0x00464424: "CDM: track %d lenght:%s" */
inline const char GS_CONTROL_SAVE_SETTINGS[] = "CONTROL: trying to save settings";  /* 0x00464580: "CONTROL: trying to save settings" */
inline const char GS_HIGHSCORE_DEFAULT_NAME[] = "Bernie Boulder";  /* 0x00465dd4: "Bernie Boulder" */
/* Game's lifecycle (game.cpp). */
inline const char GS_GAME_CD_OK[] = "GAME: original CD is in the drive - OK";  /* 0x004653f8: "GAME: original CD is in the drive - OK" */
inline const char GS_GAME_CD_MISSING[] = "GAME: * warning * - the original CD is not in drive";  /* 0x004653c4: "GAME: * warning * - the original CD is not in drive" */
inline const char GS_GAME_CREATED[] = "GAME: game-object created, game is named as:%s";  /* 0x00465394: "GAME: game-object created, game is named as:%s" */
inline const char GS_GAME_FILE_FAILED[] = "GAME: ** error ** game-file named as %s.gam could not loaded - aborting!!!";  /* 0x00465348: "GAME: ** error ** game-file named as %s.gam could not loa..." */
inline const char GS_GAME_NO_SAVES[] = "GAME: warning - no save-files for this game (maybe started a new game the first time\077), creating %d empty slots";  /* 0x004652d8: "GAME: warning - no save-files for this game (maybe starte..." */
inline const char GS_GAME_CFG_DEFAULTS[] = "GAME: warning - no correct config-values (or no *.cfg-file), creating default-config";  /* 0x00465274: "GAME: warning - no correct config-values (or no *.cfg-fil..." */
inline const char GS_GAME_CFG_LOADED[] = "GAME: config-values loaded";  /* 0x00465258: "GAME: config-values loaded" */
inline const char GS_GAME_NO_HIGHSCORES[] = "GAME: warning - no highscore-file for the game found! Creating a new one...";  /* 0x0046520c: "GAME: warning - no highscore-file for the game found! Cre..." */
inline const char GS_GAME_HIGHSCORES_LOADED[] = "GAME: highscore-file loaded";  /* 0x004651f0: "GAME: highscore-file loaded" */
inline const char GS_GAME_DEMO_ABORT[] = "GAME: ** error ** this is a DEMO, piracy alert, aborting!!!";  /* 0x004651b4: "GAME: ** error ** this is a DEMO, piracy alert, aborting!!!" */
inline const char GS_GAME_COMMERCIAL[] = "GAME: this is a commercial version";  /* 0x00465190: "GAME: this is a commercial version" */
inline const char GS_GAME_DEMO_LEVEL[] = "DemoLevelForest";  /* 0x00465420: "DemoLevelForest" */
inline const char GS_GAME_DTOR_START[] = "GAME: starting destructor";  /* 0x004654f0: "GAME: starting destructor" */
inline const char GS_GAME_HIGHSCORES_SAVED[] = "GAME: highscore-files saved";  /* 0x004654d4: "GAME: highscore-files saved" */
inline const char GS_GAME_SOUNDS_RELEASED[] = "GAME: all sounds successful released";  /* 0x00465430: "GAME: all sounds successful released" */
inline const char GS_GAME_FILE_PATH[] = "%s\134%s.gam";  /* 0x004661cc: "%s\\%s.gam" */
inline const char GS_GAME_FILE_LOADING[] = "GAME: load game-file: %s";  /* 0x004661b0: "GAME: load game-file: %s" */
inline const char GS_MODE_READ[] = "r";  /* 0x00464200: "r" */
inline const char GS_GAME_FILE_BINARY[] = "GAME: load game-file as binary,coded file";  /* 0x00466184: "GAME: load game-file as binary,coded file" */
inline const char GS_GAME_FILE_BINARY_DONE[] = "GAME: game-file loaded %d levels included %d bytes loaded";  /* 0x00466148: "GAME: game-file loaded %d levels included %d bytes loaded" */
inline const char GS_GAME_FILE_LEVEL[] = "GAME: game-file: %s";  /* 0x00466134: "GAME: game-file: %s" */
inline const char GS_GAME_FILE_TEXT[] = "GAME: load game-file as text-file";  /* 0x00466110: "GAME: load game-file as text-file" */
inline const char GS_GAME_FILE_TEXT_DONE[] = "GAME: game-file loaded %d levels included";  /* 0x004660e4: "GAME: game-file loaded %d levels included" */
inline const char GS_ACT_TURN_LEFT[] = "John_Turn_Left";  /* 0x00464570: "John_Turn_Left" */
inline const char GS_ACT_TURN_RIGHT[] = "John_Turn_Right";  /* 0x00464560: "John_Turn_Right" */
inline const char GS_ACT_MOVE_FORWARD[] = "John_Move_Forward";  /* 0x0046454c: "John_Move_Forward" */
inline const char GS_ACT_MOVE_BACK[] = "John_Move_Back";  /* 0x0046453c: "John_Move_Back" */
inline const char GS_ACT_ZOOM_IN[] = "John_Zoom_In";  /* 0x0046452c: "John_Zoom_In" */
inline const char GS_ACT_ZOOM_OUT[] = "John_Zoom_Out";  /* 0x0046451c: "John_Zoom_Out" */
inline const char GS_ACT_RELEASE_BOMB[] = "John_Release_Bomb";  /* 0x00464508: "John_Release_Bomb" */
inline const char GS_ACT_HARAKIRI[] = "John_Harakiri";  /* 0x004644f8: "John_Harakiri" */
inline const char GS_ACT_OVERVIEW[] = "John_OverView";  /* 0x004644e8: "John_OverView" */
inline const char GS_ACT_CAM_RIGHT[] = "CamModeRight";  /* 0x004644d8: "CamModeRight" */
inline const char GS_ACT_CAM_LEFT[] = "CamModeLeft";  /* 0x004644cc: "CamModeLeft" */
inline const char GS_ACT_CAM_UP[] = "CamModeUp";  /* 0x004644c0: "CamModeUp" */
inline const char GS_ACT_CAM_DOWN[] = "CamModeDown";  /* 0x004644b4: "CamModeDown" */
inline const char GS_CONTROL_NO_DEVICES[] = "Eingabeger\344te konnten nicht belegt werden";  /* 0x00464480: "Eingabegeraete konnten nicht belegt werden" */
inline const char GS_CONTROL_NO_INPUT[] = "Steuerung konnte nicht erstellt werden";  /* 0x00464458: "Steuerung konnte nicht erstellt werden" */
inline const char GS_CONTROL_ERROR_CAPTION[] = "Error!";  /* 0x004644ac: "Error!" */

/* --- KEY: keypress.cpp -- the configured action names --- */
inline const char GS_KEY_CAM_MODE_DOWN[] = "CamModeDown";  /* 0x004644b4: "CamModeDown" */
inline const char GS_KEY_CAM_MODE_UP[] = "CamModeUp";  /* 0x004644c0: "CamModeUp" */
inline const char GS_KEY_CAM_MODE_LEFT[] = "CamModeLeft";  /* 0x004644cc: "CamModeLeft" */
inline const char GS_KEY_CAM_MODE_RIGHT[] = "CamModeRight";  /* 0x004644d8: "CamModeRight" */
inline const char GS_KEY_OVERVIEW[] = "John_OverView";  /* 0x004644e8: "John_OverView" */
inline const char GS_KEY_HARAKIRI[] = "John_Harakiri";  /* 0x004644f8: "John_Harakiri" */
inline const char GS_KEY_RELEASE_BOMB[] = "John_Release_Bomb";  /* 0x00464508: "John_Release_Bomb" */
inline const char GS_KEY_ZOOM_OUT[] = "John_Zoom_Out";  /* 0x0046451c: "John_Zoom_Out" */
inline const char GS_KEY_ZOOM_IN[] = "John_Zoom_In";  /* 0x0046452c: "John_Zoom_In" */
inline const char GS_KEY_MOVE_BACK[] = "John_Move_Back";  /* 0x0046453c: "John_Move_Back" */
inline const char GS_KEY_MOVE_FORWARD[] = "John_Move_Forward";  /* 0x0046454c: "John_Move_Forward" */
inline const char GS_KEY_TURN_RIGHT[] = "John_Turn_Right";  /* 0x00464560: "John_Turn_Right" */
inline const char GS_KEY_TURN_LEFT[] = "John_Turn_Left";  /* 0x00464570: "John_Turn_Left" */

/* --- D3D: createdevice.cpp -- device bring-up, in the authors' German --- */
inline const char GS_D3D_ERR_CREATE_VP[] = "Fehler beim Anlegen des D3DViewport.";  /* 0x00464e04: "Fehler beim Anlegen des D3DViewport." */
inline const char GS_D3D_ERR_CREATE_DEVICE[] = "Fehler beim Anlegen des D3DDevice.";  /* 0x00464e2c: "Fehler beim Anlegen des D3DDevice." */
inline const char GS_D3D_ERR_ATTACH_ZBUF[] = "Fehler beim Binden des Z-Puffers an die Renderoberfl\344che.";  /* 0x00464e50: "Fehler beim Binden des Z-Puffers an die Renderoberfläche." */
inline const char GS_D3D_ERR_ZBUF_SURFACE[] = "Fehler beim Anlegen des Z-Puffers.";  /* 0x00464e8c: "Fehler beim Anlegen des Z-Puffers." */
inline const char GS_D3D_STENCIL_BITDEPTH[] = "Stencil-Buffer-Bit-Depth: %d ()\012\012";  /* 0x00464eb0: "Stencil-Buffer-Bit-Depth: %d ()\n\n" */
inline const char GS_D3D_ZBUF_BITDEPTH[] = "Z-Buffer-Bit-Depth: %d ()\012\012";  /* 0x00464ed4: "Z-Buffer-Bit-Depth: %d ()\n\n" */
inline const char GS_D3D_ERR_ZBUF_FORMAT[] = "Kein Pixelformat f\374r den Z-Puffer gefunden.";  /* 0x00464ef0: "Kein Pixelformat für den Z-Puffer gefunden." */
inline const char GS_D3D_ERR_D3D3_IFACE[] = "Direct3D3-Schnittstelle nicht gefunden.";  /* 0x00464f1c: "Direct3D3-Schnittstelle nicht gefunden." */
inline const char GS_D3D_ERR_BACKBUFFER[] = "Fehler beim Abfragen des BackBuffers.";  /* 0x00464f44: "Fehler beim Abfragen des BackBuffers." */
inline const char GS_D3D_ERR_PRIMARY[] = "Fehler beim Anlegen der prim\344ren Oberfl\344che.";  /* 0x00464f6c: "Fehler beim Anlegen der primären Oberfläche." */
inline const char GS_D3D_DONE[] = "...done\012\012";  /* 0x00464f9c: "...done\n\n" */
inline const char GS_D3D_NO_MODE_SPECIFIED[] = "no mode specified, trying to set first mode %dx%dx%d\012";  /* 0x00464fa8: "no mode specified, trying to set first mode %dx%dx%d\n" */
inline const char GS_D3D_ERR_SET_MODE[] = "Fehler beim Setzen des Videomodus.";  /* 0x00464fe0: "Fehler beim Setzen des Videomodus." */
inline const char GS_D3D_TRYING_FIRST_MODE[] = "trying to set first mode %dx%dx%d\012";  /* 0x00465004: "trying to set first mode %dx%dx%d\n" */
inline const char GS_D3D_FAILED_HR[] = "...failed (%x)\012";  /* 0x00465028: "...failed (%x)\n" */
inline const char GS_D3D_TRYING_MODE[] = "trying to set mode %dx%dx%d ";  /* 0x00465038: "trying to set mode %dx%dx%d " */
inline const char GS_D3D_END_ENUMMODES[] = "END ENUMDISPLAYMODES\012\012";  /* 0x00465058: "END ENUMDISPLAYMODES\n\n" */
inline const char GS_D3D_ERR_ENUMMODES[] = "Fehler beim Ermitteln der verf\374gbaren Videomodi.";  /* 0x00465070: "Fehler beim Ermitteln der verfügbaren Videomodi." */
inline const char GS_D3D_START_ENUMMODES[] = "START ENUMDISPLAYMODES\012";  /* 0x004650a4: "START ENUMDISPLAYMODES\n" */
inline const char GS_D3D_RENDER_BITDEPTH[] = "DeviceRenderBitDepthFlags:%d\012\012";  /* 0x004650bc: "DeviceRenderBitDepthFlags:%d\n\n" */
inline const char GS_D3D_ERR_COOP_LEVEL[] = "Fehler beim Setzen der Kooperationsebene.";  /* 0x004650dc: "Fehler beim Setzen der Kooperationsebene." */
inline const char GS_D3D_ERR_DD4_IFACE[] = "DirectDraw4-Schnittstelle nicht gefunden.";  /* 0x00465108: "DirectDraw4-Schnittstelle nicht gefunden." */
inline const char GS_D3D_ERR_DDRAW_CREATE[] = "Fehler beim Anlegen des DirectDraw-Objekts.";  /* 0x00465134: "Fehler beim Anlegen des DirectDraw-Objekts." */
inline const char GS_D3D_FOUND_MODE[] = "found mode %dx%dx%d\012";  /* 0x00465164: "found mode %dx%dx%d\n" */
inline const char GS_D3D_ZBUF_FMT[] = "Z:%d S:%d\012";  /* 0x0046517c: "Z:%d S:%d\n" */

/* --- CFG: fixedsounds.cpp -- Karoo.cfg --- */
inline const char GS_CFG_FILE[] = "Karoo.cfg";  /* 0x004652cc: "Karoo.cfg" */
inline const char GS_CFG_SAVE_ERR[] = "GAME: ** error ** while saving config-values (maybe write-protected or hd full\077) !!!";  /* 0x00465458: "GAME: ** error ** while saving config-values (maybe write-..." */
inline const char GS_CFG_SAVE_OK[] = "GAME: config-values saved correctly";  /* 0x004654b0: "GAME: config-values saved correctly" */
inline const char GS_CFG_NO_SOUND[] = "GAME: warning - SoundManager not created, no wave and CD-sound !!!";  /* 0x00465bfc: "GAME: warning - SoundManager not created, no wave and CD-s..." */

/* --- GAME: gametick.cpp / gamereset.cpp / cheatcode.cpp -- game flow --- */
inline const char GS_GAME_HSFILE[] = "jj";  /* 0x0046550c: "jj" */
inline const char GS_GAME_MAIN[] = "Main";  /* 0x00465510: "Main" */
inline const char GS_GAME_FINAL[] = "Final";  /* 0x00465518: "Final" */
inline const char GS_GAME_FINAL_DIR[] = "Final\134%s";  /* 0x00465520: "Final\\%s" */
inline const char GS_GAME_DONE_LOG[] = "GAME: game completed %d %d";  /* 0x0046552c: "GAME: game completed %d %d" */
inline const char GS_GAME_COMPLETED[] = "completed";  /* 0x00465548: "completed" */
inline const char GS_GAME_COMPLETED_AT_LEVEL[] = "GAME: completed at level %d/%d";  /* 0x00465554: "GAME: completed at level %d/%d" */
inline const char GS_GAME_GAMEOVER[] = "gameover";  /* 0x00465574: "gameover" */
inline const char GS_GAME_SWITCH_TRIGGERED[] = "GAME: switch triggered %d";  /* 0x00465580: "GAME: switch triggered %d" */
inline const char GS_GAME_JJ_GAME_END[] = "GAME: GameActions - JJ_GAME_END";  /* 0x0046559c: "GAME: GameActions - JJ_GAME_END" */
inline const char GS_GAME_GAMEFILE_ERR[] = "GAME: ** error ** game-file %s is not readable (maybe it not exists\077) aborting game!!!";  /* 0x004657a4: "GAME: ** error ** game-file %s is not readable (maybe it n..." */
inline const char GS_GAME_LEVEL_DONE_CONTINUE[] = "level completed - continue";  /* 0x00465a3c: "level completed - continue" */

/* --- LVL: levelsetup.cpp -- SetupLevelObjects --- */
inline const char GS_LVL_LEO_LOADED[] = "GAME: LEO-file %s loaded";  /* 0x004655bc: "GAME: LEO-file %s loaded" */
inline const char GS_LVL_LEO_FAILED[] = "GAME: could not load LEO:%s.leo no extra-objects in this level";  /* 0x004655d8: "GAME: could not load LEO:%s.leo no extra-objects in this l..." */
inline const char GS_LVL_WARN_CRYSTALS[] = "GAME: waring - not enough crystals to complete this level!!!!";  /* 0x00465618: "GAME: waring - not enough crystals to complete this level!..." */
inline const char GS_LVL_CRYSTALS[] = "GAME: %d crystals in this level, %d needed";  /* 0x00465658: "GAME: %d crystals in this level, %d needed" */
inline const char GS_LVL_CD_MISSING[] = "GAME: CD is not in drive! Crystal at %d,%d token!";  /* 0x00465684: "GAME: CD is not in drive! Crystal at %d,%d token!" */
inline const char GS_LVL_FREEBOMB[] = "GAME: init level - freebomb %d created";  /* 0x004656b8: "GAME: init level - freebomb %d created" */
inline const char GS_LVL_WARN_YBRIDGE[] = "GAME: waring - Y-bridge with an index lower than 1 !!!";  /* 0x004656e0: "GAME: waring - Y-bridge with an index lower than 1 !!!" */
inline const char GS_LVL_WARN_XBRIDGE[] = "GAME: waring - X-bridge with an index lower than 1 !!!";  /* 0x00465718: "GAME: waring - X-bridge with an index lower than 1 !!!" */
inline const char GS_LVL_WARN_SWITCH[] = "GAME: waring - switch with an index lower than 1 !!!";  /* 0x00465750: "GAME: waring - switch with an index lower than 1 !!!" */
inline const char GS_LVL_INIT_STARTED[] = "GAME: init level started";  /* 0x00465788: "GAME: init level started" */

/* --- OPEN: levelparse.cpp -- opening a level and its script --- */
inline const char GS_OPEN_SCRIPT_BAD_NUM[] = "GAME: could not load instruction-script:%s.jjs ,running in observation-mode only...";  /* 0x004657fc: "GAME: could not load instruction-script:%s.jjs ,running in..." */
inline const char GS_OPEN_SCRIPT_OK_NUM[] = "GAME: instruction-script loaded:%s.jjs";  /* 0x00465850: "GAME: instruction-script loaded:%s.jjs" */
inline const char GS_OPEN_FMT_SCRIPTS[] = "%s\134InstructionScripts\134%s";  /* 0x00465878: "%s\\InstructionScripts\\%s" */
inline const char GS_OPEN_FAILED_NUM[] = "GAME: ** error ** could not load level by Number (%d) (maybe it not exists\077): %s.jjm";  /* 0x00465894: "GAME: ** error ** could not load level by Number (%d) (may..." */
inline const char GS_OPEN_LOADED_NUM[] = "GAME: level (Bonus=%d) loaded by Number (%d): %s.jjm";  /* 0x004658ec: "GAME: level (Bonus=%d) loaded by Number (%d): %s.jjm" */
inline const char GS_OPEN_FMT_LEVELS[] = "%s\134Levels\134%s";  /* 0x00465924: "%s\\Levels\\%s" */
inline const char GS_OPEN_FMT_GAM[] = "%s.gam";  /* 0x00465934: "%s.gam" */
inline const char GS_OPEN_SCRIPT_BAD_NAME[] = "GAME: could not load instruction-script: %s.jjs ,running in observation-mode only...";  /* 0x0046593c: "GAME: could not load instruction-script: %s.jjs ,running i..." */
inline const char GS_OPEN_SCRIPT_OK_NAME[] = "GAME: instruction-script loaded: %s.jjs";  /* 0x00465994: "GAME: instruction-script loaded: %s.jjs" */
inline const char GS_OPEN_FAILED_NAME[] = "GAME: ** error ** could not load level by name: %s.jjm (maybe it not exists\077)";  /* 0x004659bc: "GAME: ** error ** could not load level by name: %s.jjm (ma..." */
inline const char GS_OPEN_LOADED_NAME[] = "GAME: level (Bonus=%d) loaded by name: %s.jjm";  /* 0x00465a0c: "GAME: level (Bonus=%d) loaded by name: %s.jjm" */

/* --- WAV: fixedsounds.cpp -- the seven fixed wave paths --- */
inline const char GS_WAV_SPLAT[] = "%s\134waves\134splat.wav";  /* 0x00465a58: "%s\\waves\\splat.wav" */
inline const char GS_WAV_LEVEL_COMPLETED[] = "%s\134waves\134LevelCompleted.wav";  /* 0x00465a6c: "%s\\waves\\LevelCompleted.wav" */
inline const char GS_WAV_SWITCH[] = "%s\134waves\134Switch.wav";  /* 0x00465a88: "%s\\waves\\Switch.wav" */
inline const char GS_WAV_MENU_UP_DOWN[] = "%s\134waves\134MenuUpDown.wav";  /* 0x00465a9c: "%s\\waves\\MenuUpDown.wav" */
inline const char GS_WAV_COUNT[] = "%s\134waves\134Count.wav";  /* 0x00465ab4: "%s\\waves\\Count.wav" */
inline const char GS_WAV_LAST_SECONDS[] = "%s\134waves\134LastSeconds.wav";  /* 0x00465ac8: "%s\\waves\\LastSeconds.wav" */
inline const char GS_WAV_TIME_OUT[] = "%s\134waves\134TimeOut.wav";  /* 0x00465ae4: "%s\\waves\\TimeOut.wav" */

/* --- CHEAT: cheatcode.cpp -- the typed cheat codes --- */
inline const char GS_CHEAT_LC[] = "GAME: lc %s";  /* 0x00465c6c: "GAME: lc %s" */
inline const char GS_CHEAT_LC_BY_NUMBER[] = "GAME: lc by number %d name:%s";  /* 0x00465c80: "GAME: lc by number %d name:%s" */
inline const char GS_CHEAT_FMT_LVL_PATH[] = "%s\134Levels\134%s.jjm";  /* 0x00465ca0: "%s\\Levels\\%s.jjm" */
inline const char GS_CHEAT_C_SL[] = "GAME: c - sl";  /* 0x00465cbc: "GAME: c - sl" */

/* --- RPT: reportwriter.cpp -- the level report --- */
inline const char GS_RPT_FILE[] = "LevelReport.txt";  /* 0x00465afc: "LevelReport.txt" */
inline const char GS_RPT_HSC_NAME[] = "jj.hsc";  /* 0x00465cdc: "jj.hsc" */
inline const char GS_RPT_LOG_CREATED[] = "GAME: level report created";  /* 0x00465ce4: "GAME: level report created" */
inline const char GS_RPT_SPLINES_IN[] = "\012Splines in Scripts:%d";  /* 0x00465d00: "\nSplines in Scripts:%d" */
inline const char GS_RPT_TEXTS_IN[] = "\012Texts in Scripts:%d";  /* 0x00465d18: "\nTexts in Scripts:%d" */
inline const char GS_RPT_TESTSCORES[] = "\012Testscores:%d";  /* 0x00465d30: "\nTestscores:%d" */
inline const char GS_RPT_TALLY[] = "\011\011%d\011%d\011%d\012";  /* 0x00465d40: "\t\t%d\t%d\t%d\n" */
inline const char GS_RPT_LVL_NAME[] = "** Levelname: %s\012";  /* 0x00465d5c: "** Levelname: %s\n" */
inline const char GS_RPT_LVL_FILE[] = "** Level %d  Filename:%s \012";  /* 0x00465d70: "** Level %d  Filename:%s \n" */
inline const char GS_RPT_STARS[] = "*********************************************************************\012";  /* 0x00465d8c: "**********************************************************..." */
inline const char GS_RPT_BERNIE[] = "Bernie Boulder";  /* 0x00465dd4: "Bernie Boulder" */
inline const char GS_RPT_S_TAB[] = "%s\011";  /* 0x00465de4: "%s\t" */
inline const char GS_RPT_LOG_TIME[] = "GAME: time:%d";  /* 0x00465de8: "GAME: time:%d" */
inline const char GS_RPT_BLANK_TAB[] = " \011";  /* 0x00465df8: " \t" */
inline const char GS_RPT_X_TAB[] = "X\011";  /* 0x00465dfc: "X\t" */
inline const char GS_RPT_D_TAB[] = "%d\011";  /* 0x00465e04: "%d\t" */
inline const char GS_RPT_RULE[] = "---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\012";  /* 0x00465e08: "----------------------------------------------------------..." */
inline const char GS_RPT_COLHDR2[] = "nr\011 \011level \012";  /* 0x00465f04: "nr\t \tlevel \n" */
inline const char GS_RPT_COLHDR1[] = "level-\011world\011bonus\011IS\011LEO\011Catch\011Throw\011Cryst\011HCryst\011NCryst\011HLifes\011Fields\011Obst\011Elev\011Platf\011Destr\011Glue\011Jump\011Telep\011Slide\011Ice\011Brigde\011Lifes\011Freeze\011Protect\011Paragl\011Speed\011Bomb\011Time\011Scores\012";  /* 0x00465f14: "level-\tworld\tbonus\tIS\tLEO\tCatch\tThrow\tCryst\tHCryst..." */
inline const char GS_RPT_LEVELS[] = "Levels:%d\012\012";  /* 0x00465fc8: "Levels:%d\n\n" */
inline const char GS_RPT_GAMEFILE[] = "gamefile:%s\012";  /* 0x00465fd4: "gamefile:%s\n" */
inline const char GS_RPT_TITLE[] = "***** level report ******\012\012";  /* 0x00465fe4: "***** level report ******\n\n" */
inline const char GS_RPT_LOG_CREATE[] = "GAME: create a level report";  /* 0x00466000: "GAME: create a level report" */
inline const char GS_RPT_SCRIPTTEXTS[] = "ScriptTexts.txt";  /* 0x0046601c: "ScriptTexts.txt" */
inline const char GS_RPT_MODE_W[] = "w+t";  /* 0x0046602c: "w+t" */

/* --- SND: levelsounds.cpp -- the level-based sounds --- */
inline const char GS_SND_INIT_DONE[] = "GAME: level-based sounds initialized";  /* 0x00466030: "GAME: level-based sounds initialized" */
inline const char GS_SND_LEO_SOUND[] = "GAME: try to play LEO sound %s";  /* 0x00466058: "GAME: try to play LEO sound %s" */
inline const char GS_SND_TRY_LEO[] = "GAME: try to play level-based LEO sounds";  /* 0x00466078: "GAME: try to play level-based LEO sounds" */
inline const char GS_SND_CANDY[] = "Candy";  /* 0x004660a4: "Candy" */
inline const char GS_SND_SPACE[] = "Space";  /* 0x004660ac: "Space" */
inline const char GS_SND_EGYPT[] = "Egypt";  /* 0x004660b4: "Egypt" */
inline const char GS_SND_TRY_INIT[] = "GAME: trying to init level-based sounds";  /* 0x004660bc: "GAME: trying to init level-based sounds" */

/* --- HUD: scoreoverlay.cpp -- the score overlay --- */
inline const char GS_HUD_PRESS_ENTER[] = "...press Enter";  /* 0x00466898: "...press Enter" */
inline const char GS_HUD_TOTAL_SCORE[] = "total score:";  /* 0x00466c4c: "total score:" */
inline const char GS_HUD_LEVEL_SCORE[] = "level score:";  /* 0x00466c5c: "level score:" */
inline const char GS_HUD_TIMES_1[] = "x  1 =";  /* 0x00466c6c: "x  1 =" */
inline const char GS_HUD_VITALITY[] = "vitality:";  /* 0x00466c74: "vitality:" */
inline const char GS_HUD_SISYPHUS_BONUS[] = "Sisyphus bonus:";  /* 0x00466c80: "Sisyphus bonus:" */
inline const char GS_HUD_TIMES_2[] = "x  2 =";  /* 0x00466c90: "x  2 =" */
inline const char GS_HUD_TIME_LEFT[] = "time left:";  /* 0x00466c98: "time left:" */
inline const char GS_HUD_TIMES_50[] = "x 50 =";  /* 0x00466ca4: "x 50 =" */
inline const char GS_HUD_DESTROYED_ENEMIES[] = "destroyed enemies:";  /* 0x00466cac: "destroyed enemies:" */
inline const char GS_HUD_TIMES_10[] = "x 10 =";  /* 0x00466cc0: "x 10 =" */
inline const char GS_HUD_EXTRA_CRYSTALS[] = "extra crystals:";  /* 0x00466cc8: "extra crystals:" */
inline const char GS_HUD_TIMES_5[] = "x  5 =";  /* 0x00466cd8: "x  5 =" */
inline const char GS_HUD_CRYSTALS[] = "crystals:";  /* 0x00466ce0: "crystals:" */
inline const char GS_HUD_GAME_OVER[] = "GAME OVER";  /* 0x00466cfc: "GAME OVER" */

/* --- TEX: scenetexture.cpp / texturedib.cpp / texturetga.cpp --- */
inline const char GS_TEX_GETDC_FAILED[] = "GetDC Failed\012";  /* 0x0046717c: "GetDC Failed\n" */
inline const char GS_TEX_CREATESURFACE_FAILED[] = "CreateSurface Failed\012";  /* 0x0046718c: "CreateSurface Failed\n" */
inline const char GS_TEX_LOCK_FAILED[] = "Lock Failed\012";  /* 0x004671a4: "Lock Failed\n" */
inline const char GS_TEX_FMT_PIXELFORMAT[] = ": Flags: %d, RGBBitCount: %d, RMask: %x, GMask: %x, BMask: %x, AMask: %x\012";  /* 0x004671b4: ": Flags: %d, RGBBitCount: %d, RMask: %x, GMask: %x, BMask: %x, AMask: %x\n" */
inline const char GS_TEX_NO_TEXTURE_IFACE[] = "no Texture-Interface\012";  /* 0x00467200: "no Texture-Interface\n" */
inline const char GS_TEX_NO_TGA_COPY[] = "couldn't copy TGA\012";  /* 0x00467218: "couldn't copy TGA\n" */
inline const char GS_TEX_NO_TEXTURE_SURFACE[] = "couldn't create Texture-Surface\012";  /* 0x0046722c: "couldn't create Texture-Surface\n" */
inline const char GS_TEX_FMT_Y_SIZE[] = "y-Size:%d(%g) ...ok\012";  /* 0x00467250: "y-Size:%d(%g) ...ok\n" */
inline const char GS_TEX_FMT_X_SIZE[] = "x-Size:%d(%g) ...ok\012";  /* 0x00467268: "x-Size:%d(%g) ...ok\n" */
inline const char GS_TEX_TYPE_OK[] = "Type ok\012";  /* 0x00467280: "Type ok\n" */
inline const char GS_TEX_DOT_TGA_UPPER[] = ".TGA";  /* 0x0046728c: ".TGA" */
inline const char GS_TEX_DOT_TGA_LOWER[] = ".tga";  /* 0x00467294: ".tga" */
inline const char GS_TEX_DOT_BMP_UPPER[] = ".BMP";  /* 0x0046729c: ".BMP" */
inline const char GS_TEX_DOT_BMP_LOWER[] = ".bmp";  /* 0x004672a4: ".bmp" */

/* --- LOG: gamelog.cpp -- the protocol file and the DSERR names --- */
inline const char GS_LOG_MB_TEXT[] = "Could not open Protofile";  /* 0x00467360: "Could not open Protofile" */
inline const char GS_LOG_MB_CAPT[] = "CProto::CProto(...)";  /* 0x0046737c: "CProto::CProto(...)" */
inline const char GS_LOG_BANNER[] = "\012***************** Protokollierung gestartet am : %s ***********************\012";  /* 0x00467390: "\n***************** Protokollierung gestartet am : %s ****..." */
inline const char GS_LOG_MODE_WC[] = "wc";  /* 0x004673e0: "wc" */
inline const char GS_LOG_LINE[] = "%s : %s\015\012";  /* 0x004673fc: "%s : %s\r\n" */
inline const char GS_LOG_SRCLINE[] = "%s : File: %s, Line: %d: %s \015\012";  /* 0x00467438: "%s : File: %s, Line: %d: %s \r\n" */
inline const char GS_LOG_HR_UNKNOWN[] = "Unknown HRESULT";  /* 0x00467458: "Unknown HRESULT" */
inline const char GS_LOG_DSERR_UNINITIALIZED[] = "DSERR_UNINITIALIZED";  /* 0x00467468: "DSERR_UNINITIALIZED" */
inline const char GS_LOG_DSERR_OTHERAPPHASPRIO[] = "DSERR_OTHERAPPHASPRIO";  /* 0x0046747c: "DSERR_OTHERAPPHASPRIO" */
inline const char GS_LOG_DSERR_BUFFERLOST[] = "DSERR_BUFFERLOST";  /* 0x00467494: "DSERR_BUFFERLOST" */
inline const char GS_LOG_DSERR_ALREADYINITIALIZED[] = "DSERR_ALREADYINITIALIZED";  /* 0x004674a8: "DSERR_ALREADYINITIALIZED" */
inline const char GS_LOG_DSERR_NODRIVER[] = "DSERR_NODRIVER";  /* 0x004674c4: "DSERR_NODRIVER" */
inline const char GS_LOG_DSERR_BADFORMAT[] = "DSERR_BADFORMAT";  /* 0x004674d4: "DSERR_BADFORMAT" */
inline const char GS_LOG_DSERR_PRIOLEVELNEEDED[] = "DSERR_PRIOLEVELNEEDED";  /* 0x004674e4: "DSERR_PRIOLEVELNEEDED" */
inline const char GS_LOG_DSERR_INVALIDCALL[] = "DSERR_INVALIDCALL";  /* 0x004674fc: "DSERR_INVALIDCALL" */
inline const char GS_LOG_DSERR_INVALIDPARAM[] = "DSERR_INVALIDPARAM";  /* 0x00467510: "DSERR_INVALIDPARAM" */
inline const char GS_LOG_DSERR_ALLOCATED[] = "DSERR_ALLOCATED";  /* 0x00467524: "DSERR_ALLOCATED" */
inline const char GS_LOG_DSERR_CONTROLUNAVAIL[] = "DSERR_CONTROLUNAVAIL";  /* 0x00467534: "DSERR_CONTROLUNAVAIL" */
inline const char GS_LOG_DSERR_OUTOFMEMORY[] = "DSERR_OUTOFMEMORY";  /* 0x0046754c: "DSERR_OUTOFMEMORY" */
inline const char GS_LOG_DSERR_NOAGGREGATION[] = "DSERR_NOAGGREGATION";  /* 0x00467560: "DSERR_NOAGGREGATION" */
inline const char GS_LOG_DSERR_GENERIC[] = "DSERR_GENERIC";  /* 0x00467574: "DSERR_GENERIC" */
inline const char GS_LOG_DSERR_UNSUPPORTED[] = "DSERR_UNSUPPORTED";  /* 0x00467584: "DSERR_UNSUPPORTED" */
inline const char GS_LOG_DSERR_NOINTERFACE[] = "DSERR_NOINTERFACE";  /* 0x00467598: "DSERR_NOINTERFACE" */
inline const char GS_LOG_ERRLINE[] = "%s : Error %s: %s \015\012";  /* 0x004675ac: "%s : Error %s: %s \r\n" */

/* --- PS: particles.cpp -- the particle-system loader --- */
inline const char GS_PS_NAME_NULL[] = "NULL";  /* 0x00468a60: "NULL" */
inline const char GS_PS_MSG_ENVLOAD[] = "PS: Error while loading Particlesystem, because Environment coud not loaded";  /* 0x00468a68: "PS: Error while loading Particlesystem, because Environmen..." */
inline const char GS_PS_MSG_ENVNAME[] = "PS: Error while loading Particlesystem, because Environment of Typ: '%s' coud not created";  /* 0x00468ab4: "PS: Error while loading Particlesystem, because Environmen..." */
inline const char GS_PS_MSG_NOENV[] = "PS: Error while loading Particlesystem, because could not read Environment-ClassName";  /* 0x00468b10: "PS: Error while loading Particlesystem, because could not ..." */
inline const char GS_PS_MSG_GENLOAD[] = "PS: Error while loading Particlesystem, because Generator coud not loaded";  /* 0x00468b68: "PS: Error while loading Particlesystem, because Generator ..." */
inline const char GS_PS_MSG_NOGEN[] = "PS: Error while loading Particlesystem, because Generator of Typ: '%s' coud not created";  /* 0x00468bb4: "PS: Error while loading Particlesystem, because Generator ..." */
inline const char GS_PS_MSG_NONAME[] = "PS: Error while loading Particlesystem, because could not read GeneratorclassName";  /* 0x00468c0c: "PS: Error while loading Particlesystem, because could not ..." */
inline const char GS_PS_MSG_NOLEN[] = "PS: Error while loading Particlesystem, because could not read Data";  /* 0x00468c60: "PS: Error while loading Particlesystem, because could not ..." */
inline const char GS_PS_MSG_NORING[] = "PS: Error while loading Particlesystem, because ParticleList could not created";  /* 0x00468ca4: "PS: Error while loading Particlesystem, because ParticleLi..." */
inline const char GS_PS_SRC_FILE[] = "E:\134WORK\134VC++\134JumpinJohn\134Ra\134ParticleSystem\134ParticleSystem.cpp";  /* 0x00468cf4: "E:\\WORK\\VC++\\JumpinJohn\\Ra\\ParticleSystem\\ParticleSy..." */
inline const char GS_PS_MSG_NOCOUNT[] = "PS: Error while loading Particlesystem, because ParticleCount could not read";  /* 0x00468d34: "PS: Error while loading Particlesystem, because ParticleCo..." */
inline const char GS_PS_OPENSAVE_FILE[] = "E:\134WORK\134VC++\134JumpinJohn\134Ra\134ParticleSystem\134OpenSave.cpp";  /* 0x00468e64: "E:\\WORK\\VC++\\JumpinJohn\\Ra\\ParticleSystem\\OpenSave.c..." */
inline const char GS_PS_MSG_NOCLOSE[] = "PS: ParticleSystem could not read, because File %s could not closed";  /* 0x00468e9c: "PS: ParticleSystem could not read, because File %s could n..." */
inline const char GS_PS_MSG_NOOPEN[] = "PS: Particlesystem could not read, because could not Open File %s";  /* 0x00468ee0: "PS: Particlesystem could not read, because could not Open ..." */
inline const char GS_PS_MSG_STARTREAD[] = "Starting, to Read Particlesystem from File %s ...";  /* 0x00468f24: "Starting, to Read Particlesystem from File %s ..." */
inline const char GS_PS_MSG_NOSYSTEM[] = "PS: ParticleSystem could not read, because could create System : '%s'";  /* 0x00468f58: "PS: ParticleSystem could not read, because could create Sy..." */
inline const char GS_PS_MSG_NAMEREAD[] = "PS: ParticleSystem could not read, because Data could not read";  /* 0x00468fa0: "PS: ParticleSystem could not read, because Data could not ..." */
inline const char GS_PS_MSG_NODATA[] = "PS: ParticleSystem could not read, because could not read Data";  /* 0x00468fe0: "PS: ParticleSystem could not read, because could not read ..." */
inline const char GS_PS_SUB_FILE[] = "E:\134WORK\134VC++\134JumpinJohn\134Ra\134ParticleSystem\134ParticleSystems.cpp";  /* 0x004690dc: "E:\\WORK\\VC++\\JumpinJohn\\Ra\\ParticleSystem\\ParticleSy..." */
inline const char GS_PS_MSG_PTVERTS[] = "PS: Loading PointParticleSystem failed, because could not create VertexArray";  /* 0x0046911c: "PS: Loading PointParticleSystem failed, because could not ..." */
inline const char GS_PS_MSG_SAVESIZE[] = "PS: Save FaceParticleSystem failed, because could save FaceSize";  /* 0x0046916c: "PS: Save FaceParticleSystem failed, because could save Fac..." */
inline const char GS_PS_MSG_VERTARR[] = "PS: Loading ParticleSystem failed, because could not create VertexArray";  /* 0x004691ac: "PS: Loading ParticleSystem failed, because could not creat..." */
inline const char GS_PS_MSG_FACESIZE[] = "PS: Loading FaceParticleSystem failed, because could not read FaceSize";  /* 0x004691f4: "PS: Loading FaceParticleSystem failed, because could not r..." */
inline const char GS_PS_MSG_XSAVE[] = "PS: Save XFaceParticleSystem failed, because could save Attributes";  /* 0x0046923c: "PS: Save XFaceParticleSystem failed, because could save At..." */
inline const char GS_PS_MSG_XLOAD[] = "PS: Load XFaceParticleSystem failed, because could read Attributes";  /* 0x00469280: "PS: Load XFaceParticleSystem failed, because could read At..." */

/* --- PSNAME: the particle system's own class names, generators.cpp and
 * particles.cpp.  Same .data block as the GS_PS_ messages above, but a
 * different kind: these are stored in each object's `char *pName` and
 * compared by the loader's strcmp chain, so they are `char *`, not
 * `const char *` -- the field they are assigned to is the game's. --- */
inline char GS_PSNAME_SYSTEM[] = "ParticleSystem";  /* 0x00468a38: "ParticleSystem" */
inline char GS_PSNAME_GENERATOR[] = "Generator";  /* 0x00468a48: "Generator" */
inline char GS_PSNAME_ENVIRONMENT[] = "Environment";  /* 0x00468a54: "Environment" */
inline char GS_PSNAME_POINT_SYSTEM[] = "PointParticleSystem";  /* 0x00468e40: "PointParticleSystem" */
inline char GS_PSNAME_POINT_GEN[] = "PointGenerator";  /* 0x00469024: "PointGenerator" */
inline char GS_PSNAME_BOX_GEN[] = "BoxGenerator";  /* 0x00469034: "BoxGenerator" */
inline char GS_PSNAME_STD_GEN[] = "StdGenerator";  /* 0x00469044: "StdGenerator" */
inline char GS_PSNAME_XSTD_GEN[] = "XStdGenerator";  /* 0x00469054: "XStdGenerator" */
inline char GS_PSNAME_CYL_GEN[] = "CylinderGenerator";  /* 0x00469064: "CylinderGenerator" */
inline char GS_PSNAME_GRAVITY_ENV[] = "GravityEnvironment";  /* 0x00469078: "GravityEnvironment" */
inline char GS_PSNAME_MAGNET_ENV[] = "MagnetEnvironment";  /* 0x0046908c: "MagnetEnvironment" */
inline char GS_PSNAME_FACE_SYSTEM[] = "FaceParticleSystem";  /* 0x004690b4: "FaceParticleSystem" */
inline char GS_PSNAME_XFACE_SYSTEM[] = "XFaceParticleSystem";  /* 0x004690c8: "XFaceParticleSystem" */

/* --- not a literal: the game's own mutable buffers --- */

/* --- THEME: the .thm loader and the caches it fills (theme.cpp, model.cpp,
 *     scenetexture.cpp) --- */
inline const char GS_THEME_SKY_LOADED[] = "SKY: %s loaded";  /* 0x00464784: "SKY: %s loaded" */
inline const char GS_THEME_SKY_FAILED[] = "SKY: *ERROR* failed loading %s";  /* 0x00464794: "SKY: *ERROR* failed loading %s" */
inline const char GS_THEME_SKY_UP[] = "%s_UP.tga";  /* 0x004647f0: "%s_UP.tga" */
inline const char GS_THEME_SKY_DN[] = "%s_DN.tga";  /* 0x004647e4: "%s_DN.tga" */
inline const char GS_THEME_SKY_FR[] = "%s_FR.tga";  /* 0x004647d8: "%s_FR.tga" */
inline const char GS_THEME_SKY_BK[] = "%s_BK.tga";  /* 0x004647cc: "%s_BK.tga" */
inline const char GS_THEME_SKY_LF[] = "%s_LF.tga";  /* 0x004647c0: "%s_LF.tga" */
inline const char GS_THEME_SKY_RT[] = "%s_RT.tga";  /* 0x004647b4: "%s_RT.tga" */
inline const char GS_THEME_VECTOR[] = "VECTOR(%f, %f, %f)\012";  /* 0x004646d8: "VECTOR(%f, %f, %f)\n" */
inline const char GS_THEME_SOUND_PATH[] = "%s\134%s";  /* 0x00466614: "%s\\%s" */
inline const char GS_THEME_SOUND_NONE[] = "NONE";  /* 0x00467310: "NONE" */
inline const char GS_THEME_SOUND_ADD[] = "TSM: add called (Index=%d/fn=%s)";  /* 0x004672ec: "TSM: add called (Index=%d/fn=%s)" */
inline const char GS_THEME_SOUND_RELEASING[] = "TSM: trying to release all sounds";  /* 0x00467334: "TSM: trying to release all sounds" */
inline const char GS_THEME_SOUND_RELEASED[] = "TSM: all sounds released";  /* 0x00467318: "TSM: all sounds released" */
inline const char GS_SOUNDMGR_LOG_NAME[] = "SoundManager.log";  /* 0x004678a0: "SoundManager.log" */
inline const char GS_TM_LOADED[] = "TM: %s loaded";  /* 0x004672ac: "TM: %s loaded" */
inline const char GS_TM_FOUND[] = "TM: %s found";  /* 0x004672bc: "TM: %s found" */
inline const char GS_TM_FAILED[] = "TM: *ERROR* failed loading %s";  /* 0x004672cc: "TM: *ERROR* failed loading %s" */
inline const char GS_MM_LOADED[] = "MM: %s loaded";  /* 0x00466fe0: "MM: %s loaded" */
inline const char GS_MM_FOUND[] = "MM: %s found";  /* 0x00466ff0: "MM: %s found" */
inline const char GS_MM_FAILED[] = "MM: *ERROR* failed loading %s";  /* 0x00467000: "MM: *ERROR* failed loading %s" */

#endif  /* KAROO_GAMESTR_H */
