#!/usr/bin/env python3
"""slice_launcher.py -- cut the launcher's bitmaps from three full mock-ups.

    python3 tools/slice_launcher.py data/launcher OUTDIR

data/launcher holds three 600x400 24-bit BMPs of the whole launcher window,
identical except over the buttons:
    background.bmp   no buttons
    unselected.bmp   every button in its normal state
    selected.bmp     every button in its focused state

Writes to OUTDIR the files openroo.rc embeds and windev/launcher.cpp draws:
    launcher_bg.bmp                    the background, whole
    launcher_{play,setup,quit}_{off,foc}.bmp
                                       each button's rectangle from the
                                       unselected / selected mock-up
    launcher_layout.h                  the window size and button rectangles

The button rectangles are BUTTONS below, chosen to enclose each label and
its arrows with a margin.  The script refuses to run if the mock-ups differ
anywhere outside them, so a redrawn mock-up whose buttons moved is caught.

The painted title bar and its minimise / close boxes (TITLE_H, MIN_BOX,
CLOSE_BOX) are hit-tested by windev/launcher.cpp: the window has no real
frame.

Standard library only.
"""
import os
import struct
import sys

W, H = 600, 400

# name: (x, y, w, h) in window pixels.
BUTTONS = {
    "play":  (366, 111, 216, 36),
    "setup": (366, 150, 216, 36),
    "quit":  (366, 188, 216, 36),
}
TITLE_H = 27                    # rows 0..26 drag the window
MIN_BOX = (533, 4, 20, 22)      # x, y, w, h
CLOSE_BOX = (574, 4, 22, 22)

# Channel difference (sum of R, G, B) below which pixels count as equal.
TOLERANCE = 60


def read_bmp(path):
    """Rows top to bottom, each a bytes of W*3 BGR."""
    data = open(path, "rb").read()
    if data[:2] != b"BM":
        sys.exit(f"{path}: not a BMP")
    off, = struct.unpack_from("<I", data, 10)
    hsize, w, h, planes, bpp, comp = struct.unpack_from("<IiiHHI", data, 14)
    if (w, abs(h), bpp, comp) != (W, H, 24, 0):
        sys.exit(f"{path}: want {W}x{H} 24-bit uncompressed, got "
                 f"{w}x{h} {bpp}-bit compression {comp}")
    stride = (W * 3 + 3) & ~3
    rows = [data[off + r * stride: off + r * stride + W * 3] for r in range(H)]
    return rows if h < 0 else rows[::-1]


def write_bmp(path, rows):
    h, w = len(rows), len(rows[0]) // 3
    stride = (w * 3 + 3) & ~3
    pad = b"\0" * (stride - w * 3)
    bits = b"".join(r + pad for r in reversed(rows))
    hdr = struct.pack("<2sIHHI", b"BM", 54 + len(bits), 0, 0, 54)
    info = struct.pack("<IiiHHIIiiII", 40, w, h, 1, 24, 0, len(bits),
                       2835, 2835, 0, 0)
    with open(path, "wb") as fh:
        fh.write(hdr + info + bits)


def crop(rows, x, y, w, h):
    return [r[x * 3:(x + w) * 3] for r in rows[y:y + h]]


def inside_button(x, y):
    return any(bx <= x < bx + bw and by <= y < by + bh
               for bx, by, bw, bh in BUTTONS.values())


def check_outside(bg, other, name):
    for y in range(H):
        a, b = bg[y], other[y]
        if a == b:
            continue
        for x in range(W):
            d = sum(abs(a[x * 3 + i] - b[x * 3 + i]) for i in range(3))
            if d > TOLERANCE and not inside_button(x, y):
                sys.exit(f"{name}: differs from background.bmp at ({x},{y}), "
                         "outside every button rectangle")


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, out = sys.argv[1:]
    bg = read_bmp(os.path.join(src, "background.bmp"))
    off = read_bmp(os.path.join(src, "unselected.bmp"))
    foc = read_bmp(os.path.join(src, "selected.bmp"))
    check_outside(bg, off, "unselected.bmp")
    check_outside(bg, foc, "selected.bmp")

    os.makedirs(out, exist_ok=True)
    write_bmp(os.path.join(out, "launcher_bg.bmp"), bg)
    for name, r in BUTTONS.items():
        write_bmp(os.path.join(out, f"launcher_{name}_off.bmp"), crop(off, *r))
        write_bmp(os.path.join(out, f"launcher_{name}_foc.bmp"), crop(foc, *r))

    lines = ["/* Generated by tools/slice_launcher.py -- do not edit. */",
             "#pragma once",
             f"#define LAUNCHER_W {W}",
             f"#define LAUNCHER_H {H}",
             f"#define LAUNCHER_TITLE_H {TITLE_H}"]
    for name, r in list(BUTTONS.items()) + [("min", MIN_BOX), ("close", CLOSE_BOX)]:
        lines.append(f"#define LAUNCHER_{name.upper()}_RECT " + ", ".join(map(str, r)))
    with open(os.path.join(out, "launcher_layout.h"), "w") as fh:
        fh.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
