# Fails if a header or source file outside the platform groups includes
# <windows.h>, so Win32 types and calls cannot leak into game code.  The one
# exception is the executable's WinMain in src/app/exemain_windows.cpp.
set(platform_groups windev inputdev audiodev sysdev videodev)
file(GLOB_RECURSE files "${SOURCE_DIR}/src/*.cpp" "${SOURCE_DIR}/src/*.h")
foreach(file IN LISTS files)
    set(skip FALSE)
    foreach(group IN LISTS platform_groups)
        if(file MATCHES "/src/${group}/")
            set(skip TRUE)
        endif()
    endforeach()
    if(file MATCHES "/src/app/exemain_windows.cpp$")
        set(skip TRUE)
    endif()
    if(skip)
        continue()
    endif()
    file(STRINGS "${file}" bad REGEX "^[ \t]*#[ \t]*include[ \t]*<windows.h>")
    if(bad)
        file(RELATIVE_PATH rel "${SOURCE_DIR}" "${file}")
        message(SEND_ERROR "${rel}: <windows.h> outside the platform groups; use core/portable.h or a platform-group API")
    endif()
endforeach()
